### ISSUE TITLE
adding a refresh Button, which refresh the page without lost search query

### ISSUE THREAD

**Issue by erth5** [apih/laravel-route-list-web#1]
After Doing changes I would like refresh the Route List Page to see changes. By Refresh F5, the Search input will lost
Can be added a Refresh Button to prevent them?

**Comment by apih** [comment]
It should be possible. I will try adding it later.

**Comment by apih** [comment]
@erth5 In the latest release, there is a refresh button for getting the latest routes. Thanks for your suggestion.

**Comment by erth5** [comment]
Thank you for Integration
